/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CoupleBond: typeof import('./components/couple/CoupleBond.vue')['default']
    CoupleCatch: typeof import('./components/couple/CoupleCatch.vue')['default']
    CoupleCeremony: typeof import('./components/couple/CoupleCeremony.vue')['default']
    CoupleCollapsible: typeof import('./components/couple/CoupleCollapsible.vue')['default']
    CoupleComfort: typeof import('./components/couple/CoupleComfort.vue')['default']
    CoupleDining: typeof import('./components/couple/CoupleDining.vue')['default']
    CoupleEcho: typeof import('./components/couple/CoupleEcho.vue')['default']
    CoupleFactory: typeof import('./components/couple/CoupleFactory.vue')['default']
    CoupleMemory: typeof import('./components/couple/CoupleMemory.vue')['default']
    CoupleMood: typeof import('./components/couple/CoupleMood.vue')['default']
    CoupleProfile: typeof import('./components/couple/CoupleProfile.vue')['default']
    CoupleQuest: typeof import('./components/couple/CoupleQuest.vue')['default']
    CoupleQuestion: typeof import('./components/couple/CoupleQuestion.vue')['default']
    CoupleSetup: typeof import('./components/couple/CoupleSetup.vue')['default']
    CoupleStreak: typeof import('./components/couple/CoupleStreak.vue')['default']
    CoupleSurprise: typeof import('./components/couple/CoupleSurprise.vue')['default']
    CoupleWish: typeof import('./components/couple/CoupleWish.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCheckTag: typeof import('element-plus/es')['ElCheckTag']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElStep: typeof import('element-plus/es')['ElStep']
    ElSteps: typeof import('element-plus/es')['ElSteps']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    EmojiPicker: typeof import('./components/im/EmojiPicker.vue')['default']
    GlobalSearchPanel: typeof import('./components/im/GlobalSearchPanel.vue')['default']
    ImageLightbox: typeof import('./components/im/ImageLightbox.vue')['default']
    ImAvatar: typeof import('./components/im/ImAvatar.vue')['default']
    MessageBubble: typeof import('./components/im/MessageBubble.vue')['default']
    NewMessageToast: typeof import('./components/im/NewMessageToast.vue')['default']
    ProfileDialog: typeof import('./components/im/ProfileDialog.vue')['default']
    PwaInstallGuide: typeof import('./components/im/PwaInstallGuide.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
